добавлен presentation слой для location
AsanovAlbek/FourPaws pull request #11
Opened 2022-10-17 20:48 UTC by Ameise-github

+ добвлен BaseFragment с обработкой свплывающих окон
+ добавлен SingleLiveEvent

Есть одна проблема с которой не могу справиться, когда во LocationViewModel через commands хочу показать диалоговое окно, то оно не отрабатывает.

2022-10-17 21:04 UTC, NLCodeTeam requested changes

2022-10-17 21:04 UTC, NLCodeTeam commented on app/src/main/java/epic/legofullstack/fourpaws/feature/base/BaseFragment.kt
> +        val snackbar = Snackbar
в одну строчку, переносить смысла не имеет

2022-10-17 21:04 UTC, NLCodeTeam commented on app/src/main/java/epic/legofullstack/fourpaws/feature/base/SingleLiveEvent.kt
> +    private val mPending = AtomicBoolean(false)
никаких префиксов, просто pending

2022-10-17 21:04 UTC, NLCodeTeam commented on app/src/main/java/epic/legofullstack/fourpaws/feature/location/presentation/LocationViewModel.kt
> +    val areasState: LiveData<List<Area>> get() = _areas
Откуда state это взялся второй ? у тебя 2 экрана?

2022-10-17 21:04 UTC, NLCodeTeam commented on app/src/main/java/epic/legofullstack/fourpaws/feature/location/presentation/adapter/AreaAdapter.kt
> +        val textView = currentView!!.findViewById<View>(R.id.autoCompleteTextViewItem) as TextView
что я говорил по поводу !! ?

2022-10-17 21:04 UTC, NLCodeTeam commented on app/src/main/java/epic/legofullstack/fourpaws/feature/location/presentation/adapter/AreaAdapter.kt
> +            override fun performFiltering(p0: CharSequence?): FilterResults {
p0 ?

2022-10-17 21:04 UTC, NLCodeTeam commented on app/src/main/java/epic/legofullstack/fourpaws/feature/location/presentation/adapter/AreaAdapter.kt
> +            override fun publishResults(p0: CharSequence?, p1: FilterResults?) {
p1 ?

2022-10-19 16:52 UTC, Ameise-github commented on app/src/main/java/epic/legofullstack/fourpaws/feature/location/presentation/LocationViewModel.kt
> +    val areasState: LiveData<List<Area>> get() = _areas
Исправлено. Используется copy

2022-10-19 16:52 UTC, Ameise-github commented on app/src/main/java/epic/legofullstack/fourpaws/feature/location/presentation/adapter/AreaAdapter.kt
> +        val textView = currentView!!.findViewById<View>(R.id.autoCompleteTextViewItem) as TextView
убрано

2022-10-19 18:06 UTC, NLCodeTeam approved these changes

2022-10-19 18:06 UTC, NLCodeTeam commented on app/src/main/java/epic/legofullstack/fourpaws/feature/location/presentation/LocationViewModel.kt
> +                    is ResponseState.Error -> handleError(result.isNetworkError) //showErrorDialog(resourcesProvider.getString(R.string.location_error_text))
убрать коммент с кодом

2022-10-19 18:40 UTC, merged