presentation слой для карты приютов
AsanovAlbek/FourPaws pull request #16
Opened 2022-10-30 07:51 UTC by Ameise-github

+ вывод списка приютов
+ показ адреса приюта на карте

2022-10-31 20:20 UTC, NLCodeTeam requested changes

2022-10-31 20:20 UTC, NLCodeTeam commented on app/src/main/java/epic/legofullstack/fourpaws/feature/map/presentation/ShelterMapFragment.kt
> +        private const val URI_MARKET = "market://details?id=com.google.android.apps.maps"
это можно доставать из ресурсов

2022-10-31 20:20 UTC, NLCodeTeam commented on app/src/main/java/epic/legofullstack/fourpaws/feature/map/presentation/ShelterMapFragment.kt
> +        private const val PACKAGE_MAPS = "com.google.android.apps.maps"
и это

2022-10-31 20:20 UTC, NLCodeTeam commented on app/src/main/java/epic/legofullstack/fourpaws/feature/map/presentation/ShelterMapViewModel.kt
> +    val effect = _effect.receiveAsFlow()
так и что тут происходит?

2022-11-03 21:22 UTC, Ameise-github commented on app/src/main/java/epic/legofullstack/fourpaws/feature/map/presentation/ShelterMapFragment.kt
> +        private const val URI_MARKET = "market://details?id=com.google.android.apps.maps"
исправлено

2022-11-03 21:22 UTC, Ameise-github commented on app/src/main/java/epic/legofullstack/fourpaws/feature/map/presentation/ShelterMapFragment.kt
> +        private const val PACKAGE_MAPS = "com.google.android.apps.maps"
исправлно

2022-11-04 16:32 UTC, NLCodeTeam approved these changes

2022-11-04 16:32 UTC, NLCodeTeam commented on app/src/main/java/epic/legofullstack/fourpaws/feature/base/BaseFragment.kt
> +            Uri.parse("geo:0,0?q=$latitude,$longitude")
это тоже в ресурсы можно вынести потом

2022-11-04 18:48 UTC, merged