T10-1
AsanovAlbek/FourPaws pull request #4
Opened 2022-09-29 23:44 UTC by Ameise-github

+ навигация приложения в зависимости от имеющихся настроект города

2022-09-30 22:43 UTC, NLCodeTeam requested changes

2022-09-30 22:43 UTC, NLCodeTeam commented on app/src/main/java/epic/legofullstack/fourpaws/core/data/CityPreferenceDataStore.kt
> +        return sharedPreferences.getString(USER_CITY, null)
SharedPrefs не оч хорошее решение, у него есть аналоги лучше заюзать их

2022-09-30 22:43 UTC, NLCodeTeam commented on app/src/main/java/epic/legofullstack/fourpaws/core/domain/repository/DataStoreRepository.kt
> +class DataStoreRepository(
Название не отражает сути дейтсвия

2022-09-30 22:43 UTC, NLCodeTeam commented on app/src/main/java/epic/legofullstack/fourpaws/core/domain/usecase/PreferenceGlobalUseCase.kt
> +    suspend fun getUserCity(): String? {
достаточно написать так = withContext(Dispatchers.IO) { dataStore.getUserCity() }

2022-09-30 22:43 UTC, NLCodeTeam commented on app/src/main/java/epic/legofullstack/fourpaws/feature/location/presentation/LocationFragment.kt
> +        sharedPreferences = this.requireActivity().getSharedPreferences("settings_4Paws", AppCompatActivity.MODE_PRIVATE)
как думаешь где это должно быть?

2022-09-30 22:43 UTC, NLCodeTeam commented on app/src/main/java/epic/legofullstack/fourpaws/feature/location/presentation/LocationViewModel.kt
> +class LocationViewModel() : ViewModel() {
не надо добавлять пустые классы

2022-09-30 22:43 UTC, NLCodeTeam commented on app/src/main/res/values/strings.xml
> +    <string name="b_choose_city">Выбрать</string>
название типа такого choose_city_title

2022-09-30 22:43 UTC, NLCodeTeam commented on app/src/main/res/values/strings.xml
> +    <string name="OK">OK</string>
все ресурсы должны быть в нижнем регистре

2022-10-01 14:30 UTC, Ameise-github commented on app/src/main/java/epic/legofullstack/fourpaws/feature/location/presentation/LocationFragment.kt
> +        sharedPreferences = this.requireActivity().getSharedPreferences("settings_4Paws", AppCompatActivity.MODE_PRIVATE)
Это еще не доделано. Лучше тогда просто уберу.

2022-10-02 20:55 UTC, NLCodeTeam approved these changes

2022-10-02 20:55 UTC, NLCodeTeam commented on app/src/main/java/epic/legofullstack/fourpaws/application/MainViewModel.kt
> +                .flowOn(Dispatchers.IO)
обработку ошибок не забудь накинуть потом на flow

2022-10-02 22:20 UTC, Ameise-github commented on app/src/main/java/epic/legofullstack/fourpaws/application/MainViewModel.kt
> +                .flowOn(Dispatchers.IO)
Хорошо

2022-10-02 22:26 UTC, merged